### ISSUE TITLE
Some correct ISBNs are not recognized as ISBNs

### ISSUE THREAD

**Issue by wanradt** [briandfoy/business-isbn#13]
Hi!

I suddenly experienced that some new ISBN13s are not recognized by `Business::ISBN` module, it may be related to group 9916, in following example first ISBN is fine but second is not.

```
use Business::ISBN;

foreach my $wannabe ( qw/ 9789985984093 9789916120453 / ) {
  say "W: $wannabe ?";
  my $isbn = Business::ISBN->new( $wannabe );
  say  $isbn->as_string . " GROUP CODE: " . $isbn->group_code;
  say "GROUP: " . $isbn->group;
}

```

I checked out, that the second ISBN is correct for 2 different checkers:
http://www.hahnlibrary.net/libraries/isbncalc.html
https://www.isbn-check.com/

Wbr,

Gunnar

**Comment by wanradt** [comment]
I can confirm, that your data-module `Business::ISBN::Data` does not mirror the recent state of ISBN Ranges from https://www.isbn-international.org/range_file_generation, at least new Estonian group 9916 is missing. Hope you have relevant tools to regenerate this module from authoritative source and PR would be meaningless.

**Comment by briandfoy** [comment]
I'm working on this now.

Note that you can always use a different _RangeMessage.xml_ file with different or updated data. From Business::ISBN::Data:

> If you want to use a different F<RangeMessage.xml> file, you can set
the C<ISBN_RANGE_MESSAGE> environment variable to the alternate location
before you load C<Business::ISBN>. This way, you can use the latest (or
even earlier) data without having to install something new or wait for
an update to this module.

I've included a message in the Business::ISBN docs to note that.

Thanks,
