### ISSUE TITLE
Some valid 979 ISBN's are considered invalid

### ISSUE THREAD

**Issue by ricofreak** [briandfoy/business-isbn#25]
```
use Business::ISBN; 
use Data::Dumper;

my $isbn = Business::ISBN->new('9798986969305');

warn Data::Dumper::Dumper( $isbn->is_valid );
```

This outputs an empty string:

    $VAR1 = '';

**Comment by briandfoy** [comment]
Which version of Business::ISBN and Business::ISBN::Data are you using? Update [Business::ISBN::Data](https://metacpan.org/pod/Business::ISBN::Data) and try again if you are behind; that module is up to date with the latest ranges. You can also download the latest RangeMessage.xml directly and set its location in the `ISBN_RANGE_MESSAGE` environment variable. Note that the ISBN Agency updates its data several times a month.

Note that you don't need to use Dumper on `is_valid`. It's just a scalar.

Here's a program to try:

```
use v5.10;

use Business::ISBN;
use Data::Dumper;

say "Business::ISBN: ", Business::ISBN->VERSION;
say "Business::ISBN::Data: ", Business::ISBN::Data->VERSION;

my $isbn = Business::ISBN->new('9798986969305');

say $isbn->is_valid ? 'Valid' : 'Invalid';
```

With this I get that a valid ISBN:

```
Business::ISBN: 3.008
Business::ISBN::Data: 20231130.001
Valid
```

If this still doesn't work for you after you update, please reopen this ticket.
