### ISSUE TITLE
Downgrade Mojo to recommended

### ISSUE THREAD

**Issue by rehsack** [briandfoy/business-isbn#4]
After studying your changes for 2.010, it seems to be sane to downgrade the Mojo requirement to recommends, but add a requirement or recommendation for LWP::Simple.

**Comment by briandfoy** [comment]
Most of this stuff will be ripped out soon since the xisbn service will shut down this year.

**Comment by rehsack** [comment]
No successor planned?

**Comment by mrenvoize** [comment]
From my understanding oclc aren't intending to provide any new alternatives and I'm unaware of any other service offering similar functionality. 

If anyone is aware of an alternative, I'd be happy to submit a pull request with such a change.
