### ISSUE TITLE
Is 2.010 suitable for release ?

### ISSUE THREAD

**Issue by zarniwhoop73** [briandfoy/business-isbn#5]
When I check for new versions of the modules I build, I look at what CPAN is offering. Occasionally, there are multiple versions on offer from search.cpan and I can see that one is not intended a stable release. But for Business-ISBN only 2.010 is found, and yet the revision history says "Promote to a developer release".

**Comment by briandfoy** [comment]
2.010 is a stable release. I used the wrong word and have updated the Changes file.
