### ISSUE TITLE
Ability to check checksum on invalid ISBN's

### ISSUE THREAD

**Issue by stompro** [briandfoy/business-isbn#6]
Hello, it doesn't seem possible to check the checksum on invalid ISBN that have failed for one of the following checks, prefix, group code, publisher code or article code.

The is_valid_checksum method only works if the constructor has set the checksum value, which never happens if the isbn fails one of the other checks.  The documentation seems to imply that is_valid_checksum will work even if the ISBN isn't considered valid... but maybe I'm just reading that wrong.

Maybe the docs just need to be more clear about the fact that it will only return GOOD_ISBN for valid checksums if the isbn is also valid.  Unless fix_checksum is called first?

``` perl
=item is_valid_checksum
Returns C<Business::ISBN::GOOD_ISBN> for valid checksums and
C<Business::ISBN::BAD_CHECKSUM> otherwise. This does not guarantee
that the rest of the ISBN is actually assigned to a book.
=cut

sub is_valid_checksum {
    my $self = shift;

    cluck "is_valid_checksum: Didn't get object!" unless ref $self;

    no warnings 'uninitialized';
    return GOOD_ISBN if $self->checksum eq $self->_checksum;

    return BAD_CHECKSUM;
    }
```

My use case is that Baker & Taylor generates their own ISBN's for DVD's that they sell.  Those ISBN's have valid checksums, but fail the group code check.  I would like to just check the checksum for those ISBN's, but that doesn't seem possible without calling fix_checksum first, which isn't intuitive since I don't need to fix the checksum, I just need the current checksum loaded.
Reference: https://bugs.launchpad.net/evergreen/+bug/1559281

Thanks
Josh

**Comment by briandfoy** [comment]
I recommend creating a custom Business::ISBN::Data and inserting the fake group code. This is one of the reasons I broke out the Data module from the rest of it.

The Data stuff really just inserts a data structure into the main namespace, so you might even be able to mess with that. A method like insert_group_code() might be interesting in this case.

**Comment by briandfoy** [comment]
I recommend creating a custom Business::ISBN::Data and inserting the fake group code. This is one of the reasons I broke out the Data module from the rest of it.

The Data stuff really just inserts a data structure into the main namespace, so you might even be able to mess with that. A method like insert_group_code() might be interesting in this case.

I think there's a way to work within what's already there to get this done. If you come up with something interesting, send a pull request!

Thanks,

**Comment by briandfoy** [comment]
I played around with this for a bit. It's pretty easy, so I don't see a reason to change anything:

``` perl
$Business::ISBN::country_data{ '631' } = [
    'Baker and Taylor',
    [ '0' => '9' ],
    ];
```

I don't know what the publisher codes should be. 

I've made a complete example script using the test cases from this thread: https://github.com/briandfoy/business-isbn/blob/master/examples/private_group_code.pl
