### ISSUE TITLE
Version 2.010 is logically older than version 2.09

### ISSUE THREAD

**Issue by kentfredric** [briandfoy/business-isbn#7]
``` bash
 perl -Mversion -E' say for sort { version->parse($a) <=> version->parse($b) } 
           qw( 2.01 2.02 2.07 2.08 2.09 2.09_01 2.09_02 2.010 2.010_01 )'
```

``` bash
2.01    # oldest
2.010
2.010_01
2.02
2.07
2.08
2.09
2.09_01
2.09_02 # newest
```

**Comment by kentfredric** [comment]
Just fwiw, this introduces a problem for vendors that we can't simply fix with a reindex force like possibly happened on CPAN.

Because 2.05 is already "In tree", there's no sensible way we can solve this while retaining version semantics, because a direct mapping/normalisation of 2.010 maps to the same place 2.01 maps. ( Because we're respecting Perl conventions in our mapping logic )

The best I can do is ship 2.010 under the umbrella of 2.09_02 + (some number) in the hope we don't have to keep doing this long term, and there will be eventually a natural successor to 2.09.

**Comment by kentfredric** [comment]
Kinda broken on Perl for dependency resolution also.

``` shell
perl -MBusiness::ISBN\ 999 -e1 
# Business::ISBN version 999 required--this is only version 2.09.
perl -MBusiness::ISBN\ 2.010 -e1 
#
```

**Comment by mrenvoize** [comment]
#2 may be relevant here

**Comment by greeneg** [comment]
Still broken in 2.011 with the same problem. The only solution might be to change the version scheme to drop the 0 in the minor number, making the eventual 2.012 be 2.12 instead.
