### ISSUE TITLE
LICENSE does not agree with lib/Business/ISBN.pm

### ISSUE THREAD

**Issue by ppisar** [briandfoy/business-isbn#9]
Business-ISBN-3.002 has weird license declaration. While LICENSE file quotes Artistic 2.0 license, lib/Business/ISBN.pm (and other module) files declares "same terms as Perl itself" and that means GPL+ or Artistic 1 (see http://dev.perl.org/licenses/).

The current wordings implies that lib/Business/ISBN.pm (and other module) files are covered by GPL+ or Artistic 1 licenses and the other files like Makefile.PL, examples are covered by Artistic 2.0 license.

Is that really what the author wants?

**Comment by briandfoy** [comment]
This should be fixed in 3.003. I've clarified that everything should be Artistic 2.0.
